### ISSUE TITLE
Not working properly on modern VLC

### ISSUE THREAD

**Issue by zenozenolo123** [brusiks/multi-language-video-player#2]
I tried installing it on modern versions of vlc, I can play and stop the video but cannot pause nor navigate through the progress bar.

I even tried with older versions of vlc but could not make it work properly.

It would be helpful to at least know what versions of vlc are supported.

**Comment by brusiks** [comment]
hi, thank you for the information. I'll try to fix the bug in few days.

**Comment by zenozenolo123** [comment]
Hi, sorry for not replying earlier I've been quite busy, thanks for your reply

Anyway, I was just wondering, did you manage to have a look at it? 
Any news? :)

**Comment by brusiks** [comment]
Hi, I've found time to do some fixes. Added new release and updated [README](https://github.com/brusiks/multi-language-video-player/blob/master/README.md)
Right now there is a small problem with audio sync, it's not very convenient but should work.
I've tested it on VLC version 3.0.8

**Comment by zenozenolo123** [comment]
I see, I'll check it out soon, (hoping that you could fix this last out-of-sync bug)
 thank you very much
